---
title: "Budget Justification"
date: "\\vspace{-3em}"
output: 
  pdf_document:
   includes:
    in_header: style/preamble.tex
   template: null
   keep_tex: no
   number_sections: false
documentclass: style/nsf2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\newsection{G}

## A. Senior Personnel

Eu nunc risus massa in mauris facilisi nibh pulvinar sapien. Dis viverra ipsum, nulla finibus pharetra, interdum sodales. Nulla nisi nam et fames volutpat sem leo varius urna. Purus inceptos ridiculus maecenas porttitor. Sed eu faucibus eget ut, sed cum, efficitur quisque, et sociosqu finibus. Sit accumsan cursus varius. Cubilia, lorem ac nulla porta aliquam sed pharetra quam aptent gravida. Ut, mauris mi hendrerit quis interdum bibendum cum dapibus. Ante eros mollis tincidunt ante et ut fermentum habitant, nec fusce sociosqu eu ut integer adipiscing.


## B. Other Personnel

We are requesting support for one Postdoctoral Scholar with expertise in demographic modeling or the analysis of time-series data (to be recruited) to carry out the proposed analyses in collaboration with the PI and Senior Personnel. The Postdoc will be based in Bruna’s Lab at the University of Florida; the requested salary of $48,000 is highly competitive (especially given the low cost-of-living in Gainesville, FL) and includes a 3% cost-of-living increase in Year 2. Although the postdoc and senior researchers will work as a team on the research, Bruna will be responsible for working with the postdoc to develop and implement their mentoring plan.

## C. Fringe Benefits

Fringe benefits for UF Postdoctoral Researchers are calculated at the rate of 12.1% established by the UF Division of Sponsored Research (DSR) and include a comprehensive health insurance plan and benefits package.

## E. Travel

We are requesting funds for both domestic and foreign travel for project personnel.

a.	Domestic: We are requesting funds for the postdoctoral researcher to travel to Columbia University for 14 days each year to learn advanced statistical methods, carry out analyses, and prepare manuscripts with Uriarte. We are also requesting funds for the postdoc and PI to attend conferences to present research results in Years 1 & 2. Both of these are important to the postdoc’s professional development; while at Columbia they will be able to interact with Uriarte’s research group and present a departmental seminar. The amount requested for the Postdoc in Year 1 includes airfare ($500), per diem at the UF rate ($1120), and miscellaneous expenses such as in-city transportation ($500). The amount requested for the Bruna and the Postdoc in Year 2 includes airfare ($650), per diem at the UF rate ($640, 14 days @ $80 per day), and miscellaneous expenses such as in-city transportation and meeting registration ($800) for each.

b.	Foreign: We feel it is essential for the postdoc to learn first-hand about the study system and site, as well as how the survey data forming the basis of their analyses are collected. We are therefore requesting funds for the Postdoc to travel from the US to Manaus with Bruna in Year 1 to visit the field sites, help carry out an annual census, present research at INPA, and engage with INPA students and faculty. The amount requested ($3200 for each) includes funds for US-Manaus airfare ($1400), miscellaneous expenses such as in-city transportation and visas ($500), 4 days of per diem for Manaus ($320, 4 days @ $80 per day), and 10 days of BDFFP station fees ($980) for each. Note that station fees include food and transportation to and from the BDFFP camps as well as stipend, food, and transportation for a BDFFP technician to accompany the team.

## G. Other Direct Costs

a.	Materials and Supplies: We are requesting $500 for miscellaneous books, materials, and supplies related to the project (including any needed for the field trip, computer programming or statistics books, data storage, software licenses, etc.). We are also requesting $1500 in Year 1 for a computer; the amount requested reflects the percentage of time that the computer will be used for this specific project (75%).

b.	Publication costs: We are requesting $1500 each year to defray the costs of publishing research results in open-access journals and archiving data at the Dryad Digital Repository. 

c.	Consulting Services: None

d.	Computer Services: None. 

e.	Subcontracts: None


## H. Indirect Costs

Indirect Costs are calculated at the UF rate of 52.5%.


