---
title: "Postdoctoral Mentoring Plan"
date: "\\vspace{-3em}"
output: 
  pdf_document:
   includes:
    in_header: style/preamble.tex
   template: null
   keep_tex: no
   number_sections: false
documentclass: style/nsf2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\newsection{J2}
# Postdoctoral Mentoring Plan

**1) Creation of an Individual Development Plan (IDP).** We will use the process developed by the National Postdoctoral Association (2012), which identifies the postdoc’s long-term career goals, the skills necessary to meet them, and the means of developing these skills. It also lays out mutual expectations and milestones for the current project.

**2) Development of Essential Professional Skills.** The following skills are essential for postdocs exploring a variety of professional paths (CSPP 2000), but this list is by no means exhaustive and will be modified based on the needs identified in the IDP. (1) Fundraising: We will encourage our postdoc to submit proposals to support their research interests; they will receive mentorship in writing proposals from the Senior Personnel and will be able to participate in formal grant-writing training activities at UF. (2) Teaching & Mentoring: The postdoc will be allowed to participate in UF workshops on teaching and have opportunities to guest lecture in Bruna’s courses and – if appropriate – develop and teach a 1-unit seminar for undergraduates on a topic of their choice. Finally, our postdoc will develop mentorship skills by working with UF undergraduates interested in conducting research projects related to the project. 

**3) Publishing:** PIs will work closely with the postdoc as they prepare manuscripts; to further practice identifying strengths and weaknesses in alternative ways to present and interpret results we will also provide opportunities to serve as a reviewer of manuscripts submitted to the journals for which we are Editors. Because we consider reading broadly and remaining abreast of developments in the field critical to writing good papers, the postdoc will also participate in our journal club. (4) Communication skills: Participation in weekly lab meetings is an opportunity to practice presentations and give/receive constructive criticism on the framing of presentations and presentation materials. The postdoc will also present in the UF and Yale seminar series, which is an opportunity to develop the seminar required for many job interviews (including for positions outside the academy). Finally, their involvement in a multi-national partnership will allow them to hone the skills necessary in an increasingly globalized scientific environment.  (5) Career advancement. As career opportunities arise we will advise on applying for positions – academic, the private sector, NGOs – tips for negotiating salary and start-up funds, planning a research program, etc.  

**4) Expanding of Professional Networks:** To increase their professional networks, the postdoc will be encouraged to meet with seminar speakers and other visitors, as well as become involved with the emerging networks of postdocs affiliated with academic societies (e.g., the Student and Early Career Scientists Chapter of the ATBC, INNGE). We also will encourage the postdoc to either to co-organize a symposium at a professional meeting on a topic relevant to our research project; we have found this to be one of the best ways in which we were able to expand our professional networks and develop new collaborations.

**5) Regular review of progress and final evaluation.** The postdoc will have an annual evaluation with Bruna (who will solicit feedback from the other Senior Researchers) to provide formal feedback on their progress. The postdoc will also have an exit interview with the WEC Dept. Chair to provide feedback on the positive aspects of their tenure, insights into how the experience could be improved, and to provide feedback on the mentorship provided by the PIs.


CSPP. 2000. Enhancing the Postdoctoral Experience for Scientists and Engineers: A Guide for Postdoctoral Scholars, Advisers, Institutions, Funding Organizations, and Disciplinary Societies. Committee On Science, Engineering, & Public Policy, National Academy of Sciences, National Academy of Engineering, Institute of Medicine, National Academy Press, Washington DC.

National Postdoctoral Association. 2012. Developing a Postdoctoral Mentoring Plan.
